---
id: pipeline.json
"$schema": "http://json-schema.org/draft-04/schema"
title: Pipeline definition
description: ""
type:
- object
properties:
  name:
    name: name
    type: string
    description: Pipeline name
    example: 'Release Pipeline'
  description:
    name: description
    type: string
    description: Longer textual description of the module
    example: 'Release Automatiohn Pipeline'
  inputs:
    name: inputs
    type: array
    description: Definition of Pipeline input operations
    minItems: 0
    uniqueItems: true
    items:
      "$ref": "operation.json"
  outputs:
    name: outputs
    type: array
    description: Definition of Pipeline output operations
    minItems: 0
    uniqueItems: true
    items:
      "$ref": "operation.json"
  processes:
    name: processes
    description: Processes provided by the Pipeline
    minItems: 0
    uniqueItems: true
    items:
      "$ref": "process.json"
  connections:
    name: connections
    description: Connections provided by the Pipeline
    minItems: 0
    uniqueItems: true
    items:
      "$ref": "connection.json" 
required: [name,processes,connections]
